# Generated by Django 5.0.6 on 2024-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('inprogress', 'Inprogress'), ('notstarted', 'Notstarted'), ('fail', 'Fail')], default='Done', max_length=100)),
                ('technology_use', models.CharField(max_length=1500)),
                ('date_created', models.DateTimeField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
